In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense,Conv2D,MaxPooling2D,Flatten
from keras.datasets import mnist
from keras.utils import to_categorical

In [2]:
model=Sequential()
model.add(Conv2D(32,(5,5),activation='relu',input_shape=(28,28,1)))
model.add(MaxPooling2D((2,2),))

model.add(Conv2D(64,(5,5),activation='relu'))
model.add(MaxPooling2D(2,2))

model.add(Flatten())
model.add(Dense(10,activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 24, 24, 32)        832       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 12, 12, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 8, 8, 64)          51264     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 4, 4, 64)          0         
_________________________________________________________________
flatten (Flatten)            (None, 1024)              0         
_________________________________________________________________
dense (Dense)                (None, 10)                10250     
Total params: 62,346
Trainable params: 62,346
Non-trainable params: 0
____________________________________________________

In [3]:
(train_images,train_labels),(test_images,test_labels)=mnist.load_data()


11493376/11490434 [==============================] - 0s 0us/step


In [4]:
train_images.shape

(60000, 28, 28)

In [5]:
train_images=train_images.reshape((60000,28,28,1))
train_images=train_images.astype('float32')/255
train_images.shape

(60000, 28, 28, 1)

In [6]:
test_images = test_images.reshape((10000, 28, 28, 1))
test_images = test_images.astype('float32') / 255
test_images.shape

(10000, 28, 28, 1)

In [7]:
train_labels=to_categorical(train_labels)

In [8]:
train_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [9]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [10]:
test_labels=to_categorical(test_labels)
test_labels

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [11]:
model.compile(loss='categorical_crossentropy',optimizer='sgd',metrics=['accuracy'])

In [12]:
model.fit(train_images,train_labels,batch_size=100,epochs=10)

Epoch 1/10
600/600 [==============================] - 34s 3ms/step - loss: 1.4104 - accuracy: 0.6174
Epoch 2/10
600/600 [==============================] - 2s 3ms/step - loss: 0.2869 - accuracy: 0.9155
Epoch 3/10
600/600 [==============================] - 2s 3ms/step - loss: 0.2071 - accuracy: 0.9392
Epoch 4/10
600/600 [==============================] - 2s 3ms/step - loss: 0.1633 - accuracy: 0.9528
Epoch 5/10
600/600 [==============================] - 2s 3ms/step - loss: 0.1379 - accuracy: 0.9596
Epoch 6/10
600/600 [==============================] - 2s 3ms/step - loss: 0.1187 - accuracy: 0.9645
Epoch 7/10
600/600 [==============================] - 2s 3ms/step - loss: 0.1081 - accuracy: 0.9692
Epoch 8/10
600/600 [==============================] - 2s 3ms/step - loss: 0.0958 - accuracy: 0.9717
Epoch 9/10
600/600 [==============================] - 2s 3ms/step - loss: 0.0841 - accuracy: 0.9747
Epoch 10/10
600/600 [==============================] - 2s 3ms/step - loss: 0.0823 - accuracy: 0.975

In [14]:
test_loss,test_acc=model.evaluate(test_images,test_labels)
print(test_loss)
print(test_acc)

313/313 [==============================] - 1s 2ms/step - loss: 0.0659 - accuracy: 0.9804
0.06593145430088043
0.980400025844574
